version: '3'

services:
   camm:
     build:
        context: .
     devices:
       - "/dev/video0:/dev/video0"
     ports:
       - "8081:8081"
       - "8090:8090"
     restart: always
     env_file:
       - variables.env
